### PR TITLE
Bumped up the Gradle, Gradle Plugin and dependency versions.

### PR DESCRIPTION
**Pull request by nikhilbansal97**
This PR updates the gradle versions and dependencies as many students were reporting that they were facing problems in importing the projects and each student had to manually update the versions.

### CODE REVIEW

**Review by Kvaibhav01 — APPROVED** [review]

**Comment by nikhilbansal97** [comment]
Hey @Kvaibhav01 should I wait for someone else to review the PR or I can merge it?

**Comment by Kvaibhav01** [comment]
You can merge it. There seems no conflict here.

**Comment by nikhilbansal97** [comment]
@Kvaibhav01 After this PR will be merged, the other branches also have to be updated. So, should I create a PR for all the branches or you can update them? I think merging the `starting-point` branch into other ones should do it.

**Comment by Kvaibhav01** [comment]
You can create your own branch and merge. @udacity's team will check the rest.

**Comment by nikhilbansal97** [comment]
@Kvaibhav01 Okay. You can merge this PR. I don't have the write access.

**Comment by Kvaibhav01** [comment]
Neither do I have! @udacity members will have write access.

**Comment by SudKul** [comment]
We have upgraded the code in the **lesson-four** branch to AndroidX in this [commit](https://github.com/udacity/ud843-QuakeReport/commit/5685f5c1881b738a394514abedc48dce0f2ad342). We expect students to replicate the similar updates to other branches, where needed. 

We recommend you use the https://knowledge.udacity.com/ platform to discuss individual issues with our experienced mentors.

**Pull request closed without merging**
