### PR TITLE
Lesson four

### PR DESCRIPTION
**Pull request by ahmdshrif**

### CODE REVIEW

**Comment by samuelchapas** [comment]
Recenly I fixed the code by fixing the ArrayList parameter in the EarthquakeAdapter to List<earthquake>.

**Comment by samuelchapas** [comment]
lokeshbysani, yes I followed as you said and it worked, first I was trying to look for any wrong data type with the instances or object but everything was fine until the List in the parameter of the adapter was wrong, I was working with an array list instead of a list. With the change that you proposed there is no difference between the time loading the data, it helps me to see that the http connection must be handled to get a fit reponse in time, because previously I didn't wait to see the data only close and I was thinking that something was wrong with my code by resulting in the lost of time.
Please check my code, I made a backup.
https://github.com/samuelchapas/udacity/tree/master/app/src/main/java/com/example/android/quakereport

Thank you for your help. 
We can contact you in order to request you for help?

**Review by akshjsr — COMMENTED** [review]
--------- beginning of crash
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.example.android.quakereport, PID: 2242
                  java.lang.NullPointerException: Attempt to invoke virtual method 'void com.example.android.quakereport.EarthquakeAdapter.clear()' on a null object reference
                      at com.example.android.quakereport.EarthquakeActivity$EarthquakeAsyncTask.onPostExecute(EarthquakeActivity.java:111)
                      at com.example.android.quakereport.EarthquakeActivity$EarthquakeAsyncTask.onPostExecute(EarthquakeActivity.java:91)
                      at android.os.AsyncTask.finish(AsyncTask.java:660)
                      at android.os.AsyncTask.-wrap1(AsyncTask.java)
                      at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
                      at android.os.Handler.dispatchMessage(Handler.java:102)
                      at android.os.Looper.loop(Looper.java:154)
                      at android.app.ActivityThread.main(ActivityThread.java:6077)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)
Application terminated.
 


 please help @samuelchapas 
link to my code : 
https://github.com/akshjsr/Quake_Report.git

**Comment by Ihnatsiuk** [comment]
If somebody got empty screen with working app, just try increase timeout in QueryUtils. It helped me:

HttpURLConnection urlConnection = null;
        InputStream inputStream = null;
        try {
            urlConnection = (HttpURLConnection) url.openConnection();
            urlConnection.setReadTimeout(45000 /* milliseconds */);                 // original 10000
            urlConnection.setConnectTimeout(60000 /* milliseconds */);           // original 15000

**Comment by Kvaibhav01** [comment]
@Ihnatsiuk I got that empty screen while building the APK file and installing it in my phone. I solved this by updating 
`private static final String USGS_REQUEST_URL = "http://earthquake.usgs.gov/fdsnws/event/1/query";`
to
`private static final String USGS_REQUEST_URL ="https://earthquake.usgs.gov/fdsnws/event/1/query";`

You can see this change [here](https://github.com/udacity/ud843-QuakeReport/pull/77/commits/f59f3c5e5017d7051edf4f939f20d2ddf20f33a3#diff-686b8ca5399cef982d0b832c08866fa1L48).

**Pull request closed without merging**
